theme: minima
title: Amateur
author: Kensuits
email: kensuits@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This site is just for learning purposes.

# social links
twitter_username: @NiNjAK3NNY
github_username:  Kensuits

show_excerpts: true # set to false to remove excerpts on the homepage
